---

- hosts: all
  become: true
  tasks:
  
  - name: install apache and php package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ php_module_package }}"
      state: latest
      update_cache: yes

  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: started
      enabled: yes
      name: httpd
    when: ansible_facts['distribution'] == "Archlinux" 

  - name: Create an index.html file with a greeting message.
    ansible.builtin.copy:
      dest: /srv/http/index.html
      content: |
        <html>
         <title>Welcome</title>
          <body>
           <h2>Welcome to my server</h2>
          </body>
        </html>
      owner: root
      group: root
      mode: '0644' 
    when: ansible_facts['distribution'] == "Archlinux"

