---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Install updates
    tags: always
    pacman:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Archlinux"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php package
    tags: apache,php-apache,ArchLinux
    package:
      name: 
        - apache
        - php 
        - php-apache 
      state: latest
    when: ansible_facts['distribution'] == "Archlinux" 

  - name: Make sure a service unit is running
    tags: service, httpd
    ansible.builtin.systemd_service:
      state: started
      enabled: yes
      name: httpd
    when: ansible_facts['distribution'] == "Archlinux" 

  - name: Create an index.html file with a greeting message.
    tags: apache,apache2,httpd 
    ansible.builtin.copy:
      dest: /srv/http/index.html
      src: default_site.html
      owner: root
      group: root
      mode: '0644' 
    when: ansible_facts['distribution'] == "Archlinux"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: mariadb,db,Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"   
      
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
